### ISSUE TITLE
Generate ethereum address from public key

### ISSUE THREAD

**Issue by binary1101** [Sailias/cryptocoin_payable#3]
It's not secure to use mnemonic on server. It's better to calculate ethereum addresses corresponding to an extended public key.

**Comment by mhluska** [comment]
I can update this. At the time I went with mnemonic because I couldn't find a way to generate extended public keys for Ethereum.

What's the reasoning for it being less secure? Presumably it would be stored in an env variable rather than source code similar to other secret tokens.

**Comment by Sailias** [comment]
The other secret tokens use the MPK and can only generate public keys, never the private keys.

**Comment by mhluska** [comment]
I'm waiting on a reply in the [money-tree repo](https://github.com/GemHQ/money-tree/issues/25#issuecomment-367811863) for some advice on this.  It's a little beyond my knowledge without diving deep into the HD wallet spec. Let's see what they say before I go that route.

**Comment by mhluska** [comment]
I merged a fix for this.
