### ISSUE TITLE
money-tree dependency causes heroku deployments to fail

### ISSUE THREAD

**Issue by jmarbach** [Sailias/cryptocoin_payable#5]
https://github.com/Sailias/cryptocoin_payable/blob/551c4bd6e0905c018f0647f9f0e704e09dbdf531/cryptocoin_payable.gemspec#L32

Please update the `money-tree` dependency to the more actively maintained fork: https://github.com/GemHQ/money-tree 

This fork has fixed money-tree 0.9.0's `libssl-dev` issue that prevents apps using cryptocoin_payable from being deployed to Heroku's `heroku-16` stack: 
https://github.com/GemHQ/money-tree/pull/23

**Comment by mhluska** [comment]
I can take care of this early this week. Otherwise, if you want to submit a PR, I'd be happy to merge.

I'm using the following workaround in my project to deploy to Heroku:
```
gem 'money-tree', github: 'GemHQ/money-tree', branch: :master
```

**Comment by jmarbach** [comment]
@mhluska I'm happy to try my best with a PR but my lack of experience makes me unsure! 

I understand that gemspec files do not accept dependencies from source code repositories. So, is this fix as simple as adding your suggested workaround to this repository's gemfile?

**Comment by mhluska** [comment]
@jmarbach I looked into this and it doesn't seem like there's a way forward until the GemHQ fork publishes a gem. See https://github.com/GemHQ/money-tree/issues/27
