### ISSUE TITLE
Remittance

### ISSUE THREAD

**Issue by mhluska** [Sailias/cryptocoin_payable#7]
@Sailias my app has a need to pay out users periodically (as well as collect payments on their behalf which this gem already covers). Would it make sense to add this feature to cryptocoin_payable? I'm envisioning this as just an extra method to each coin adapter that will interact with the correct API (e.g. Blockcypher for btc). And then wrapped in a Rake task.

**Comment by Sailias** [comment]
@mhluska I don't see the need for this to be part of the Gem.  If you are configuring the access keys for the APIs this gem is consuming, I would add the remittance logic outside of this gem.  Also keep in mind this Gem accepts payments using your own MPK (in Bitcoin) and an adapter only needs to query the blockchain.  An adapter that can also send payments is not necessary.

I would like to keep all forms of remittance out of this gem and in the hands of the parent application if possible.
